### ISSUE TITLE
superheat makes greys for hyperintense values

### ISSUE THREAD

**Issue by jamesdalg** [rlbarter/superheat#32]
superheat(X = submatrix,membership.rows = row_block_ids,membership.cols = col_block_ids,left.label = "cluster",bottom.label = "cluster",force.bottom.label = T,force.left.label = T,
          grid.hline.col = "white",
          grid.vline.col = "white",
          grid.hline.size = 2,
          grid.vline.size = 2,scale=T,heat.pal = c("green","black","red"),heat.pal.values = c(-0.5,0,0.5))
![image](https://user-images.githubusercontent.com/26911077/36567734-72aed26a-17f5-11e8-95da-4ad3077af010.png)

**Comment by jamesdalg** [comment]
![image](https://user-images.githubusercontent.com/26911077/36567742-7f7bdd9e-17f5-11e8-991c-d400a76227e8.png)

**Comment by rlbarter** [comment]
In general, please provide a reproducible example so that I can run your code myself (e.g. I do not have access to `submatrix` so cannot see what the data looks like where the superheat function sets the color to grey).

The problem may also be that you are only providing colors for quantiles (-0.5, 0, 0.5) leaving the ranges outside that undefined (i.e. from -1 to -0.5 and from 0.5 to 1). 

You can also try setting `extreme.values.na = FALSE` (this will set any values outside the given range to the max/min color rather than NA). You can also play with the `heat.lim` argument.

Many of these concepts are discussed in sections 4.2, and 4.3 of the vignette (https://rlbarter.github.io/superheat/heatmap-colormap.html#color-transitions)
