### ISSUE TITLE
Keeping vector order in `membership.rows` option

### ISSUE THREAD

**Issue by seantma** [rlbarter/superheat#38]
@rlbarter Thanks again for this awesome package!

I want to ask if it's possible to preserve the original order in the vector I provide to `membership.rows` option in `superheat`. Currently, the program seems to *sort* the vector order automatically. 

Below is some sample code to reproduce this question. I'm manually assigning a `group` vector to my random matrix.
```
set.seed(100)
mat <- matrix(runif(100, min = -1, max = 1),ncol=10)
group <- sample(letters, 10)

superheat(mat)

superheat(mat,
          membership.rows = group)
```
The results are below. Rather than keeping the original matrix order, the new heatmap is _self sorted_ by the `group` value which I did not intend to.

Is there a way to preserve the vector order I've provided to `membership.rows` or `membership.col`? 

<img width="535" alt="screen shot 2018-07-20 at 3 06 54 pm" src="https://user-images.githubusercontent.com/915443/43020698-e7700774-8c2e-11e8-98eb-fe0dd549185f.png">

<img width="529" alt="screen shot 2018-07-20 at 3 09 21 pm" src="https://user-images.githubusercontent.com/915443/43020702-eba35594-8c2e-11e8-9a3d-aa746377f733.png">

**Comment by rlbarter** [comment]
Hi Sean!

Thanks for brining this to my attention. So sorry for my ultra-delayed response (I've been focusing on other projects). I've implemented a bug fix so that superheat now preserves the group order provided in `membership.rows` or `membership.cols`.  Feel free to re-open if this didn't solve your problem (if indeed you still care about this problem!)
