### ISSUE TITLE
Making superheat plot interactive

### ISSUE THREAD

**Issue by thiyangt** [rlbarter/superheat#56]
Thank you very much for this wonderful package. Is there any possibility to add an interactive layer on top of superheat plot?
I mean ggplotly(<superheat plot>).

**Comment by rlbarter** [comment]
Hello!

At the moment, no, sadly. I unfortunately don't have the bandwidth to look into this at the moment, especially since I suspect implementing this won't be trivial. In the meantime, you might want to look into the iheatmapr package, which is interactive already: https://github.com/ropensci/iheatmapr 

Rebecca

**Comment by thiyangt** [comment]
Thanks a lot.
